### ISSUE TITLE
Mock api implementation [Models]

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/cadl-ranch#39]
Creating an issue for the missing implementations now that the CI enforce it 

Update here when added the test https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch/src/actions/validate-mock-apis.ts#L90

[Docs for writing mock apis](https://github.com/Azure/cadl-ranch/blob/main/docs/writing-mock-apis.md)

Use `npm run validate-mock-apis` to check everything is good or the errors(Remove the exluded line first)

  - [ ] `models/collections-basic`         @msyyc 
  - [ ] `models/collections-models`     @msyyc 
  - [ ] `models/enum-properties`        @msyyc 
  - [ ] `models/inheritance`                  @weidongxu-microsoft 
  - [ ] `models/input-basic`                 @weidongxu-microsoft 
  - [ ] `models/readonly-properties`   @weidongxu-microsoft 
  - [ ] `models/roundtrip-basic`          @qiaozha 
  - [ ] `models/nested-models`           @qiaozha
  - [ ] `models/primitive-properties`    @qiaozha
  - [ ] `models/optional-properties`    @pshao25 
  - [ ] `models/output-basic`               @pshao25 
  - [ ] `clients/interfaces`                      @pshao25

**Comment by lirenhe** [comment]
Discussed with the team and each SDK team will pick up a couple of the time for Mock API

**Comment by annelo-msft** [comment]
We will want to also reconcile these test cases with [the efforts to port autorest.testserver tests directly](https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http#from-testserver) - we don't want to duplicate tests for given features/feature groups, so we can stay clear about which languages support which features.  If we have duplicate test cases, and different languages use different tests for the same feature, it will be hard to communicate about feature parity across languages going forward.  @lmazuel FYI.

**Comment by annelo-msft** [comment]
Per @lmazuel, please merge "smart Salmon" into inheritance/main.cadl as follows:

Add:
```
model DerivedFromBaseClassWithDiscriminatorC extends DerivedFromBaseClassWithDiscriminatorB {
  discriminatorProperty: "C";
}
```
