### ISSUE TITLE
Fix mock apis

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/cadl-ranch#41]
Creating an issue for the missing implementations now that the CI enforce it 

Update here when added the test https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch/src/actions/validate-mock-apis.ts#L90

[Docs for writing mock apis](https://github.com/Azure/cadl-ranch/blob/main/docs/writing-mock-apis.md)

Use `npm run validate-mock-apis` to check everything is good or the errors(Remove the excluded line first)

  - [ ] `resiliency/dev-driven`
  - [ ] `resiliency/dev-driven-1`
  - [ ] `resiliency/dev-driven-1`
