### ISSUE TITLE
Standardize Cadl Ranch Contributions

### ISSUE THREAD

**Issue by iscai-msft** [Azure/cadl-ranch#61]
We want to make sure that our cadl ranch tests are clean, easy to understand, and test real scenarios. As cadl ranch is growing it is becoming harder to enforce these requirements, so we want to start early and make sure we standardize cadl ranch contributions while we are still in the early stages.

These are the main issues we're going to be tackling. I'll also be reaching out to current contributors so I can understand the reason for tests and possibly workshop. Please let me know if you have any questions!

- [x] Standard quickstart for PR merging: https://github.com/Azure/cadl-ranch/issues/60
- [ ] Clean up tests and add mock API tests: https://github.com/Azure/cadl-ranch/issues/41
- [ ] Add dashboard: https://github.com/Azure/cadl-ranch/issues/15
